export interface Project {
  id: number;
  title: string;
  category: string;
  year: string;
  location: string;
  size: string;
  summary: string;
  overview: string;
  img: string;
  images: string[];
  stats: { value: string; label: string }[];
  highlights: string[];
  featured: boolean;
  span: "single" | "double";
}

/* ─────────────────────────── Data ─────────────────────────── */
/* Images verified against https://www.udgok.com/projects.html source */
export const PROJECTS: Project[] = [
  {
    id: 1,
    title: "Paradigm Oral Health",
    category: "Healthcare",
    year: "2025",
    location: "Tulsa, OK",
    size: "4,800 SF",
    summary: "State-of-the-art oral surgery center with ASSE 6010 medical gas systems, 6 operatories, sterile processing, and backup generator.",
    overview: "State-of-the-art oral surgery center featuring 6 fully-equipped exam rooms, complete medical gas installation (O2, N2O, vacuum), backup generator, advanced laboratory facilities, and dedicated sterile/dirty/clean rooms meeting the highest healthcare standards.",
    img: "/images/IMG_7608.jpeg",
    images: [
      "/images/IMG_7608.jpeg",
      "/images/IMG_7607.jpeg",
      "/images/IMG_7609.jpeg",
      "/images/IMG_7618.jpeg",
      "/images/IMG_7619.jpeg",
      "/images/IMG_7623.jpeg",
      "/images/IMG_7627.jpeg",
      "/images/IMG_7631.jpeg",
      "/images/IMG_7641.jpeg",
      "/images/IMG_7602.jpeg",
    ],
    stats: [
      { value: "6", label: "Exam Rooms" },
      { value: "3", label: "Months" },
      { value: "Full", label: "Medical Gas" },
      { value: "Nov 2025", label: "Completed" },
    ],
    highlights: [
      "6 exam rooms with full equipment",
      "Medical gas systems (O2, N2O, vacuum)",
      "Backup generator installation",
      "Sterile / dirty / clean room separation",
      "Advanced laboratory facilities",
    ],
    featured: true,
    span: "double",
  },
  {
    id: 2,
    title: "DSN Cybersecurity",
    category: "Commercial",
    year: "2025",
    location: "Tulsa, OK",
    size: "25,000 SF",
    summary: "Secure commercial headquarters with biometric access control, LED display walls, and enterprise data infrastructure.",
    overview: "A complete tenant improvement of DSN's Tulsa headquarters. The scope included biometric access control at all entry points, LED video wall installations, server room infrastructure with redundant cooling, executive conference suites, and open-plan collaboration spaces — all built to NFPA 75 data center standards.",
    img: "/images/dsn-cyber-1.jpeg",
    images: [
      "/images/dsn-cyber-1.jpeg",
      "/images/dsn-cyber-2.jpeg",
    ],
    stats: [
      { value: "25,000", label: "Square Feet" },
      { value: "Biometric", label: "Access Control" },
      { value: "NFPA 75", label: "Data Standard" },
      { value: "2025", label: "Completed" },
    ],
    highlights: [
      "Biometric access control at all entry points",
      "LED display wall and video conference rooms",
      "Server room with redundant cooling infrastructure",
      "Executive suites and open collaboration zones",
      "Full AV integration and structured cabling",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 3,
    title: "Perfect Foods Fuel Station",
    category: "Commercial",
    year: "2024",
    location: "Bixby, OK",
    size: "6,500 SF",
    summary: "Ground-up fuel & convenience destination on 2 acres with carwash, EV charging, and fresh food program.",
    overview: "A ground-up fuel and convenience destination built on 2 acres in Bixby. The project delivered a full-service carwash, 12-position EV charging canopy, branded fuel dispensers, fresh food service kitchen, and a modern interior retail environment — completed in under 6 months.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/67cbe41ca38cbd1a3a515a54_Perfect-food-image.jpg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/67cbe41ca38cbd1a3a515a54_Perfect-food-image.jpg",
    ],
    stats: [
      { value: "6,500", label: "Square Feet" },
      { value: "2 Acres", label: "Site" },
      { value: "EV Ready", label: "12 Chargers" },
      { value: "< 6 Mo", label: "Delivery" },
    ],
    highlights: [
      "Full-service automated carwash",
      "12-position EV charging canopy (350kW)",
      "Fresh food service kitchen and grab-and-go",
      "Branded fuel canopy and dispensers",
      "Modern retail interior with custom fixtures",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 4,
    title: "The Eye Institute",
    category: "Healthcare",
    year: "2024",
    location: "Tulsa, OK",
    size: "12,000 SF",
    summary: "Full design-build of a specialty ophthalmology facility with 6 medical-grade exam rooms and optical showroom.",
    overview: "A complete design-build project for one of Tulsa's leading ophthalmology practices. The Eye Institute required medical-grade finishes throughout, a precision optical showroom, six fully equipped exam rooms, and a surgical prep suite — all delivered on schedule and under budget.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e052b3ba68b4bb1790fda_Doc-Lobby%202.webp",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e052b3ba68b4bb1790fda_Doc-Lobby%202.webp",
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80",
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80",
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&q=80",
    ],
    stats: [
      { value: "6", label: "Exam Rooms" },
      { value: "12,000", label: "Square Feet" },
      { value: "Medical", label: "Grade Finishes" },
      { value: "2024", label: "Completed" },
    ],
    highlights: [
      "6 fully equipped ophthalmology exam rooms",
      "Precision optical showroom with custom millwork",
      "Medical-grade lighting and flooring throughout",
      "Surgical prep suite and sterile processing room",
      "ADA compliant design from ground up",
    ],
    featured: false,
    span: "double",
  },
  {
    id: 5,
    title: "Dayco Memphis",
    category: "Industrial",
    year: "2023",
    location: "Memphis, TN",
    size: "125,000 SF",
    summary: "Large-scale manufacturing facility with advanced automation systems and precision mechanical rooms.",
    overview: "One of our largest industrial projects — a 125,000 SF manufacturing facility for Dayco in Memphis. The project required precision coordination of advanced automation systems, high-bay MEP installation, climate-controlled production environments, and optimized material flow throughout the facility.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e00eb95a13edff0453515_dayco.jpg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e00eb95a13edff0453515_dayco.jpg",
      "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&q=80",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&q=80",
      "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&q=80",
    ],
    stats: [
      { value: "125,000", label: "Square Feet" },
      { value: "Advanced", label: "Automation" },
      { value: "High-Bay", label: "MEP Install" },
      { value: "2023", label: "Completed" },
    ],
    highlights: [
      "125,000 SF industrial manufacturing floor",
      "Advanced automation system coordination",
      "High-bay MEP installation and coordination",
      "Climate-controlled production environments",
      "Optimized material flow and logistics layout",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 6,
    title: "Historic Apartment Remodel",
    category: "Residential",
    year: "2023",
    location: "Tulsa, OK",
    size: "80 Units",
    summary: "80-unit historic building renovation with structural upgrades and full MEP system replacement.",
    overview: "Full modernization of an 80-unit historic residential building in downtown Tulsa. The project preserved the building's original architectural character while delivering complete structural reinforcement, full MEP system replacement, and modern unit renovations across all 80 apartments.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e0282d99a23e674c03624_OIP.jpg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e0282d99a23e674c03624_OIP.jpg",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
      "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80",
    ],
    stats: [
      { value: "80", label: "Units" },
      { value: "Full", label: "MEP Replaced" },
      { value: "Historic", label: "Preservation" },
      { value: "2023", label: "Completed" },
    ],
    highlights: [
      "80 fully renovated residential units",
      "Structural reinforcement and seismic upgrades",
      "Complete MEP system replacement",
      "Historic facade and character preservation",
      "Modern kitchen and bath packages throughout",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 7,
    title: "AVID Hotel Tulsa",
    category: "Hospitality",
    year: "2023",
    location: "Tulsa, OK",
    size: "87 Rooms",
    summary: "IHG-certified boutique hotel with fitness center, business lounge, and premium guest amenity package.",
    overview: "An IHG-certified AVID Hotel built to brand standard in Tulsa. The project delivered 87 guest rooms, a state-of-the-art fitness center, business lounge, and full back-of-house support spaces — all within IHG's strict prototype specifications and on a compressed 14-month schedule.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e03794dda2e92ee728302_OIP%20(1).jpg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e03794dda2e92ee728302_OIP%20(1).jpg",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80",
    ],
    stats: [
      { value: "87", label: "Guest Rooms" },
      { value: "IHG", label: "Certified" },
      { value: "14 Mo", label: "Schedule" },
      { value: "2023", label: "Completed" },
    ],
    highlights: [
      "87 IHG-certified guest rooms",
      "State-of-the-art fitness center",
      "Business lounge and meeting rooms",
      "Full back-of-house support spaces",
      "Brand prototype compliance throughout",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 8,
    title: "Swift Recon Automation",
    category: "Industrial",
    year: "2023",
    location: "Oklahoma City, OK",
    size: "45,000 SF",
    summary: "High-tech automation facility with climate-controlled server infrastructure and data centers.",
    overview: "A cutting-edge 45,000 SF technology and automation facility for Swift Recon in Oklahoma City. The project included precision climate-controlled server rooms, redundant power infrastructure, data center cabling, and a flexible production floor with raised access flooring throughout.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e0418813ffc6a400a3c42_R.png",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e0418813ffc6a400a3c42_R.png",
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80",
      "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    ],
    stats: [
      { value: "45,000", label: "Square Feet" },
      { value: "Redundant", label: "Power Systems" },
      { value: "Raised", label: "Access Floors" },
      { value: "2023", label: "Completed" },
    ],
    highlights: [
      "Climate-controlled server infrastructure",
      "Redundant power and cooling systems",
      "Raised access flooring throughout",
      "Data center cabling and structured wiring",
      "Flexible production floor with automation mounts",
    ],
    featured: false,
    span: "double",
  },
  {
    id: 9,
    title: "Candlewood Suites",
    category: "Hospitality",
    year: "2023",
    location: "Regional",
    size: "122 Suites",
    summary: "Extended-stay hotel with full kitchenette packages, business amenities, and fitness center.",
    overview: "A full extended-stay hotel build for the Candlewood Suites brand, delivering 122 fully appointed suites with complete kitchenette packages, in-suite laundry provisions, fitness center, and business facilities — all built to IHG brand standard.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e045fa78aa3ada9f2b994_3043410_17110209380058605629.jpg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e045fa78aa3ada9f2b994_3043410_17110209380058605629.jpg",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&q=80",
    ],
    stats: [
      { value: "122", label: "Suites" },
      { value: "Full", label: "Kitchenettes" },
      { value: "IHG", label: "Brand Standard" },
      { value: "2023", label: "Completed" },
    ],
    highlights: [
      "122 extended-stay suites",
      "Full kitchenette packages in all units",
      "In-suite laundry provisions",
      "Fitness center and business lounge",
      "IHG brand standard compliance",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 10,
    title: "Sinclair EV Station",
    category: "Commercial",
    year: "2027",
    location: "Oklahoma",
    size: "Upcoming",
    summary: "Next-gen fuel & EV destination with 12 high-capacity DC fast chargers and 350kW power infrastructure.",
    overview: "An upcoming next-generation fuel and EV destination for the Sinclair brand in Oklahoma. The development will include 12 high-capacity DC fast chargers at 350kW, a full food service program, trucker lounge, and expanded fuel canopy — designed to serve both passenger vehicles and commercial trucking.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e05d754992e579e480457_image%20(1).png",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e05d754992e579e480457_image%20(1).png",
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600&q=80",
    ],
    stats: [
      { value: "12", label: "EV Chargers" },
      { value: "350kW", label: "Power" },
      { value: "Trucking", label: "Ready" },
      { value: "2027", label: "Upcoming" },
    ],
    highlights: [
      "12 DC fast chargers at 350kW capacity",
      "Full food service program and trucker lounge",
      "Expanded fuel canopy for commercial vehicles",
      "Sinclair brand standards throughout",
      "Solar canopy integration planned",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 11,
    title: "Multi-State Storage & Residential",
    category: "Residential",
    year: "2022",
    location: "Rogers AR / Springfield MO",
    size: "Multi-Site",
    summary: "Multi-state self-storage and residential development with AI security analytics and climate-controlled units.",
    overview: "A multi-state self-storage development program spanning facilities in Arkansas and Missouri. Each site delivered climate-controlled unit programs, advanced security and AI-assisted analytics, digital access control, and branded exterior packages — all coordinated under a single construction management contract.",
    img: "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e079563b2e649a512d2f2_storageworld-3.jpeg",
    images: [
      "https://cdn.prod.website-files.com/66c0d7ca1ef0c151011b7d14/684e079563b2e649a512d2f2_storageworld-3.jpeg",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80",
      "https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=600&q=80",
    ],
    stats: [
      { value: "Multi", label: "State Program" },
      { value: "AI", label: "Analytics" },
      { value: "Climate", label: "Controlled" },
      { value: "2022", label: "Completed" },
    ],
    highlights: [
      "Multi-state site coordination (AR/MO)",
      "Climate-controlled storage unit programs",
      "AI-assisted security and analytics",
      "Digital access control at all sites",
      "Branded exterior and signage package",
    ],
    featured: false,
    span: "single",
  },
  {
    id: 12,
    title: "Ed Young Shopping Center",
    category: "Retail",
    year: "2024",
    location: "Bartlesville, OK",
    size: "5,500 SF",
    summary: "Retail center redevelopment with modern facade, full MEP upgrades, and ADA-compliant site work.",
    overview: "A full-scale retail center redevelopment anchored by a liquor and convenience store. The scope included new exterior facades across all tenant bays, complete MEP system replacement, ADA site improvements, parking lot reconstruction, and a new anchor tenant build-out delivered in 8 months.",
    img: "/images/edyoung-1.jpg",
    images: [
      "/images/edyoung-1.jpg",
      "/images/edyoung-2.jpg",
      "/images/edyoung-3.jpg",
    ],
    stats: [
      { value: "5,500", label: "Square Feet" },
      { value: "8 Mo", label: "Completion" },
      { value: "Full", label: "MEP Upgrade" },
      { value: "2024", label: "Completed" },
    ],
    highlights: [
      "New exterior facades across all tenant bays",
      "Complete MEP system replacement",
      "ADA-compliant parking and site work",
      "Anchor tenant build-out (liquor & convenience)",
      "Full parking lot reconstruction",
    ],
    featured: false,
    span: "single",
  },
];

export const CATEGORIES = ["All", "Healthcare", "Commercial", "Industrial", "Hospitality", "Retail", "Residential"];

export const STATS = [
  { n: "150+", l: "Projects Delivered" },
  { n: "12", l: "Project Sectors" },
  { n: "33%", l: "Faster Delivery" },
  { n: "98%", l: "Client Satisfaction" },
];